[tool.mypy]
files = ["src", "tests"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "src.models.soft_delete_mixin"
ignore_errors = true

[[tool.mypy.overrides]]
module = "src.api.api_base"
ignore_errors = true

[[tool.mypy.overrides]]
module = "requests"
ignore_missing_imports = true